"""empty message

Revision ID: 4d2e915382c7
Revises: 93612fe95336
Create Date: 2024-10-31 19:54:09.354802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2e915382c7'
down_revision: Union[str, None] = '93612fe95336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('youtube_credits', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('req_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'youtube_credits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('youtube_credits', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('logs')
    op.drop_table('channels')
    # ### end Alembic commands ###
