"""empty message

Revision ID: 7556573f21b7
Revises: 150b5a5cca81
Create Date: 2024-10-31 00:12:07.249843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7556573f21b7'
down_revision: Union[str, None] = '150b5a5cca81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscribe_end', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('youtube_credits', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'youtube_credits')
    op.drop_column('user', 'subscribe_end')
    # ### end Alembic commands ###
