"""empty message

Revision ID: 93612fe95336
Revises: 7556573f21b7
Create Date: 2024-10-31 00:15:42.728307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93612fe95336'
down_revision: Union[str, None] = '7556573f21b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('does_free_sub_used', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'does_free_sub_used')
    # ### end Alembic commands ###
