"""empty message

Revision ID: bab107b82c1c
Revises: 48206028490b
Create Date: 2024-11-04 21:24:32.024295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab107b82c1c'
down_revision: Union[str, None] = '48206028490b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('youtube_token', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'youtube_token')
    # ### end Alembic commands ###
